---

- name: "FreeBSD Redis Debug."
  vars:
    msg: |
         ansible_architecture [{{ ansible_architecture }}]
         ansible_os_family [{{ ansible_os_family }}]
         ansible_distribution [{{ ansible_distribution }}]
         ansible_distribution_major_version [{{ ansible_distribution_major_version }}]
         ansible_distribution_version [{{ ansible_distribution_version }}]
         ansible_distribution_release [{{ ansible_distribution_release }}]

         bsd_redis_enable [{{ bsd_redis_enable }}]
         bsd_redis_service [{{ bsd_redis_service }}]
         bsd_redis_conf_path [{{ bsd_redis_conf_path }}]
         bsd_redis_conf_file [{{ bsd_redis_conf_file }}]
         bsd_redis_bind_address [{{ bsd_redis_bind_address }}]
         bsd_redis_port [{{ bsd_redis_port }}]
         bsd_redis_conf_backup [{{ bsd_redis_conf_backup }}]
         bsd_redis_packages
         {{ bsd_redis_packages|to_nice_yaml }}
         bsd_redis_packages_extra
         {{ bsd_redis_packages_extra|to_nice_yaml }}

         freebsd_install_method [{{ freebsd_install_method }}]
         freebsd_use_packages [{{ freebsd_use_packages|default('UNDEFINED') }}]
  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
