---
# tasks freebsd_redis

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: bsd_redis_debug | bool
  tags: bsd_redis_debug

- name: Import pkg.yml
  ansible.builtin.import_tasks: pkg.yml
  when: bsd_redis_install | bool
  tags: bsd_redis_pkg

- name: Import redisconf.yml
  ansible.builtin.import_tasks: redisconf.yml
  tags: bsd_redis_conf

- name: Import rcconf.yml
  ansible.builtin.import_tasks: rcconf.yml
  tags: bsd_redis_rcconf

# EOF
