---

- name: "packages: Install Redis packages."
  pkgng:
    name: "{{ item }}"
  loop: "{{ bsd_redis_packages }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install Redis ports."
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_redis_packages }}"
  when: freebsd_install_method == "ports"

- name: "packages: Install Redis extra packages."
  pkgng:
    name: "{{ item }}"
  loop: "{{ bsd_redis_packages_extra }}"
  when: freebsd_install_method == "packages"

- name: "packages: Install Redis extra ports."
  portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_redis_packages_extra }}"
  when: freebsd_install_method == "ports"

# EOF
...
