---
- name: "Pkg: Install Redis packages."
  community.general.pkgng:
    name: "{{ bsd_redis_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method | lower == "packages"

- name: "Pkg: Install Redis ports."
  community.general.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_redis_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method | lower == "ports"

- name: "Pkg: Install Redis extra packages."
  community.general.pkgng:
    name: "{{ bsd_redis_packages_extra }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method | lower == "packages"

- name: "Pkg: Install Redis extra ports."
  community.general.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ bsd_redis_packages_extra }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method | lower == "ports"

# EOF
