---

- name: "rcconf: Enable and start Redis."
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*redis_enable\s*=(.*)$'
    line: 'redis_enable="YES"'
    backup: "{{ bsd_redis_backup }}"
  notify: enable and start redis
  when: bsd_redis_enable|bool

- name: "rcconf: Disable and stop Redis."
  lineinfile:
    dest: /etc/rc.conf
    regexp: '^\s*redis_enable\s*=(.*)$'
    line: 'redis_enable="NO"'
    backup: "{{ bsd_redis_backup }}"
  notify: disable and stop redis
  when: not bsd_redis_enable|bool

- meta: flush_handlers

- name: "rcconf: Wait for Redis service at port {{ bsd_redis_port }}."
  wait_for:
    port: "{{ bsd_redis_port }}"
  when: bsd_redis_enable|bool

# EOF
...
